# Generated by Django 6.1.1 on 2026-09-25 09:11

import Myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo')),
                ('heading', models.CharField(max_length=100)),
                ('sub_heading', models.CharField(max_length=100)),
                ('text_color', models.CharField(default='#000000', max_length=30)),
                ('font_size', models.PositiveIntegerField(default=16)),
                ('bg_color', models.CharField(default='#ffffff', max_length=20)),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', Myapp.models.CustomUserManager()),
            ],
        ),
    ]
