# Generated by Django 6.1.1 on 2026-09-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_website_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='id',
            field=models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False),
        ),
    ]
