# Generated by Django 6.1.1 on 2026-09-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_alter_website_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='website',
            name='logo_radius',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
