# Generated by Django 6.1.1 on 2026-09-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_website_description_website_logo_radius'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='home/')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
                ('bullet_point_1', models.CharField(max_length=100)),
                ('bullet_point_2', models.CharField(max_length=100)),
                ('bullet_point_3', models.CharField(max_length=100)),
            ],
        ),
    ]
