# Generated by Django 6.1.1 on 2026-09-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(upload_to='about/')),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_sub_title', models.CharField(max_length=300)),
                ('who_we_are_image', models.ImageField(upload_to='about/')),
                ('who_we_are_title', models.CharField(max_length=200)),
                ('who_we_are_description', models.TextField()),
                ('mission_title', models.CharField(max_length=200)),
                ('mission_description', models.TextField()),
                ('vision_title', models.CharField(max_length=200)),
                ('vision_description', models.TextField()),
                ('special_title', models.CharField(max_length=200)),
                ('special_description', models.TextField()),
            ],
        ),
    ]
