# Generated by Django 6.1.1 on 2026-10-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0007_enquiry_alter_aboutus_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('school_visit', 'School Visit'), ('medical_camp', 'Medical Camp'), ('nature_immersion', 'Nature Immersion Program'), ('wellness_retreat', 'Wellness Retreat')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('sub_title', models.CharField(max_length=300)),
                ('hero_image', models.ImageField(upload_to='activities/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
