# Generated by Django 6.1.1 on 2026-10-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='activities/videos/'),
        ),
    ]
